# Generated by Django 6.1.1 on 2026-10-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense'])), name='transaction_kind_valid', violation_error_message='Kind must be income or expense.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive', violation_error_message='Amount must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'expense'), _negated=True), models.Q(('category', ''), _negated=True), _connector='OR'), name='transaction_expense_has_category', violation_error_message='Choose a category.'),
        ),
    ]
