# Generated by Django 6.1.1 on 2026-10-05 23:52

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_integrity_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_expense_has_category',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'expense'), _negated=True), models.Q(django.db.models.lookups.Exact(django.db.models.functions.text.Trim('category'), ''), _negated=True), _connector='OR'), name='transaction_expense_has_category', violation_error_message='Choose a category.'),
        ),
    ]
