# Generated by Django 6.1.1 on 2026-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_trim_category_in_expense_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_demo',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
